# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (^LICENSE.md$|^src/VERSION$|^env/|^src/(bw/misc/root-ca.pem$|deps/src/|common/core/modsecurity/files|ui/static/(js/(editor/|utils/purify/|tsparticles\.bundle\.min\.js)|css/dashboard\.css))|\.(svg|drawio|patch\d?|ascii|tf|tftpl|key)$)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: requirements-txt-fixer
        name: Fix requirements.txt and requirements.in files
        description: Sorts entries in requirements.txt and requirements.in files.
        files: (requirements|constraints).*\.(txt|in)$
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(mkdocs.yml|examples/bigbluebutton/docker-compose.yml)$
        args: ["--allow-multiple-documents"]
      - id: check-case-conflict

  - repo: https://github.com/psf/black
    rev: 8fe627072f15ff2e3d380887b92f7868efaf6d05 # frozen: 24.4.0
    hooks:
      - id: black
        name: Black Python Formatter
        language_version: python3.9

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier
        name: Prettier Code Formatter

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: 84c370104d6a8d1eef00c80a3ebd42f7033aaaad # frozen: v0.20.0
    hooks:
      - id: stylua-github
        exclude: ^src/(bw/lua/middleclass.lua|common/core/antibot/captcha.lua)$

  - repo: https://github.com/lunarmodules/luacheck
    rev: 418f48976c73be697fe64b0eba9ea9821ac9bca8 # frozen: v1.1.2
    hooks:
      - id: luacheck
        exclude: ^src/(bw/lua/middleclass.lua|common/core/antibot/captcha.lua)$
        args: ["--std", "min", "--codes", "--ranges", "--no-cache"]

  - repo: https://github.com/pycqa/flake8
    rev: 7d37d9032d0d161634be4554273c30efd4dea0b3 # frozen: 7.0.0
    hooks:
      - id: flake8
        name: Flake8 Python Linter
        args: ["--max-line-length=160", "--ignore=E266,E402,E501,E722,W503"]

  - repo: https://github.com/dosisod/refurb
    rev: 2e31f0033b6c00bf99912fc6a8b5fd00460c9ba0 # frozen: v2.0.0
    hooks:
      - id: refurb
        name: Refurb Python Refactoring Tool
        exclude: ^tests/

  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482 # frozen: v2.2.6
    hooks:
      - id: codespell
        name: Codespell Spell Checker
        exclude: (^src/(ui/templates|common/core/.+/files|bw/loading)/.+.html|modsecurity-rules.conf.*)$
        entry: codespell --ignore-regex="(tabEl|Widgits)" --skip src/ui/static/js/utils/flatpickr.js,src/ui/static/css/style.css,CHANGELOG.md
        language: python
        types: [text]

  - repo: https://github.com/gitleaks/gitleaks
    rev: 145400593c178304246371bc45290588bc72f43e # frozen: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 2491238703a5d3415bb2b7ff11388bf775372f29 # frozen: v0.10.0
    hooks:
      - id: shellcheck
