# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: (^LICENSE.md$|^src/VERSION$|^env/|^src/(bw/misc/root-ca.pem$|deps/src/|common/core/modsecurity/files|ui/static/(js/(editor/|utils/purify/|tsparticles\.bundle\.min\.js)|css/dashboard\.css))|\.(svg|drawio|patch\d?|ascii|tf|tftpl|key)$)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: requirements-txt-fixer
        name: Fix requirements.txt and requirements.in files
        description: Sorts entries in requirements.txt and requirements.in files.
        files: (requirements|constraints).*\.(txt|in)$
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(mkdocs.yml|examples/bigbluebutton/docker-compose.yml)$
        args: ["--allow-multiple-documents"]
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier
        name: Prettier Code Formatter

  - repo: https://github.com/codespell-project/codespell
    rev: 193cd7d27cd571f79358af09a8fb8997e54f8fff # frozen: v2.3.0
    hooks:
      - id: codespell
        name: Codespell Spell Checker
        exclude: (^src/(ui/templates|common/core/.+/files|bw/loading)/.+.html|modsecurity-rules.conf.*|src/ui/static/js/lottie-web.min.js)$
        entry: codespell --ignore-regex="(tabEl|Widgits)" --skip src/ui/static/js/utils/flatpickr.js,src/ui/static/css/style.css,CHANGELOG.md
        language: python
        types: [text]

  - repo: https://github.com/gitleaks/gitleaks
    rev: 145400593c178304246371bc45290588bc72f43e # frozen: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 2491238703a5d3415bb2b7ff11388bf775372f29 # frozen: v0.10.0
    hooks:
      - id: shellcheck
