version: "3"

services:
  bunkerweb:
    build:
      context: .
      dockerfile: ./src/bw/Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - API_WHITELIST_IP=127.0.0.0/8 192.168.64.0/24
    networks:
      bw-universe:
        ipv4_address: 192.168.64.42
      bw-services:
        aliases:
          - bunkerweb

  bw-core:
    build:
      context: .
      dockerfile: ./src/core/Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - bw-data:/data
    environment:
      - TOKEN=ChangeMe42!!!
      - WHITELIST=0.0.0.0/0
      - BUNKERWEB_INSTANCES=192.168.64.42
      - API_WHITELIST_IP=127.0.0.0/8 192.168.64.0/24
      - CHECK_TOKEN=no
      - CHECK_WHITELIST=no
      - SERVER_NAME=www.example.com
      - USE_BUNKERNET=no
      - USE_BLACKLIST=no
      - USE_REVERSE_PROXY=yes
      - www.example.com_USE_UI=yes
      - www.example.com_REVERSE_PROXY_URL=/admin
      - www.example.com_REVERSE_PROXY_HOST=http://bw-ui:7000
      - www.example.com_INTERCEPTED_ERROR_CODES=404 405 413 429 500 501 502 503 504
    networks:
      - bw-universe

  bw-ui:
    # On dev, Docker is looking for ui files in local machine (allow Vite hot reload and so on...)
    # Need to npm i on .src/ui/client and .src/ui/setup
    # Then run node build on .src/ui/
    build:
      context: .
      dockerfile: ./src/ui/Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - ./src/ui/static:/usr/share/bunkerweb/ui/static
    environment:
      - CORE_ADDR=http://bw-core:1337
      - CORE_TOKEN=ChangeMe42!!!
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=P@ssw0rd
      - MODE=dev
    networks:
      - bw-universe

volumes:
  bw-data:

networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 192.168.64.0/24
  bw-services:
    name: bw-services
