version: "3"

services:
  app1:
    image: tutum/hello-world
    networks:
      - bw-services
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL_1=~ ^/app1/(.*)$$
        - bunkerweb.REVERSE_PROXY_HOST_1=http://app1/$$1

  app2:
    image: tutum/hello-world
    networks:
      - bw-services
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - bunkerweb.SERVER_NAME=www.example.com
        - bunkerweb.USE_REVERSE_PROXY=yes
        - bunkerweb.REVERSE_PROXY_URL_2=~ ^/app2/(.*)$$
        - bunkerweb.REVERSE_PROXY_HOST_2=http://app2/$$1

networks:
  bw-services:
    external: true
    name: bw-services
