name: Generate documentation PDF (REUSABLE)

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.10"
      - name: Install doc dependencies
        run: pip install --no-cache-dir --require-hashes -r docs/requirements.txt && sudo apt install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Install chromium
        run: sudo apt install chromium-browser
      - name: Install node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 18
      - name: Install puppeteer
        run: cd docs && npm install
      - name: Run mkdocs serve in background
        run: mkdocs serve & sleep 10
      - name: Run pdf script
        run: node docs/misc/pdf.js http://localhost:8000/print_page/ BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf 'BunkerWeb documentation v${{ inputs.VERSION }}'
      - uses: actions/upload-artifact@694cdabd8bdb0f10b2cea11669e1bf5453eed0a6 # v4.2.0
        with:
          name: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
          path: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
