name: Push documentation (REUSABLE)

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      ALIAS:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install doc requirements
        run: pip install -r docs/requirements.txt
      - name: Push doc
        run: mike deploy --update-aliases --push ${{ inputs.VERSION }} ${{ inputs.ALIAS }}
      - name: Set default doc
        if: inputs.ALIAS == 'latest'
        run: mike set-default --push latest
