name: Push packagecloud (REUSABLE)

on:
  workflow_call:
    inputs:
      SEPARATOR:
        required: true
        type: string
      SUFFIX:
        required: true
        type: string
      REPO:
        required: true
        type: string
      LINUX:
        required: true
        type: string
      VERSION:
        required: true
        type: string
      PACKAGE:
        required: true
        type: string
      BW_VERSION:
        required: true
        type: string
      ARCH:
        required: true
        type: string
      PACKAGE_ARCH:
        required: true
        type: string
    secrets:
      PACKAGECLOUD_TOKEN:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Check out repository code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Install ruby
        uses: ruby/setup-ruby@1198b074305f9356bd56dd4b311757cc0dab2f1c # v1.175.1
        with:
          ruby-version: "3.0"
      - name: Install packagecloud
        run: gem install package_cloud
      # Download packages
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: inputs.LINUX != 'el' && inputs.LINUX != 'el9'
        with:
          name: package-${{ inputs.LINUX }}-${{ inputs.PACKAGE_ARCH }}
          path: /tmp/${{ inputs.LINUX }}
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        if: inputs.LINUX == 'el' || inputs.LINUX == 'el9'
        with:
          name: package-rh${{ inputs.LINUX }}-${{ inputs.PACKAGE_ARCH }}
          path: /tmp/${{ inputs.LINUX }}
      # Remove existing packages
      - name: Remove existing package
        if: inputs.LINUX != 'el9' && inputs.LINUX != 'ubuntu-noble'
        run: package_cloud yank bunkerity/${{ inputs.REPO }}/${{ inputs.LINUX }}/${{ inputs.VERSION }} bunkerweb${{ inputs.SEPARATOR }}${{ inputs.BW_VERSION }}${{ inputs.SEPARATOR }}${{ inputs.SUFFIX }}${{ inputs.PACKAGE_ARCH }}.${{ inputs.PACKAGE }}
        continue-on-error: true
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      - name: Remove existing package el9
        if: inputs.LINUX == 'el9'
        run: package_cloud yank bunkerity/${{ inputs.REPO }}/el/9 bunkerweb${{ inputs.SEPARATOR }}${{ inputs.BW_VERSION }}${{ inputs.SEPARATOR }}${{ inputs.SUFFIX }}${{ inputs.PACKAGE_ARCH }}.${{ inputs.PACKAGE }}
        continue-on-error: true
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      - name: Remove existing package ubuntu-noble
        if: inputs.LINUX == 'ubuntu-noble'
        run: package_cloud yank bunkerity/${{ inputs.REPO }}/ubuntu/noble bunkerweb${{ inputs.SEPARATOR }}${{ inputs.BW_VERSION }}${{ inputs.SEPARATOR }}${{ inputs.SUFFIX }}${{ inputs.PACKAGE_ARCH }}.${{ inputs.PACKAGE }}
        continue-on-error: true
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      # Update name
      # - name: Rename package
      #   if: inputs.BW_VERSION == 'testing'
      #   run: sudo apt install -y rename && rename 's/[0-9]\.[0-9]\.[0-9]/testing/' /tmp/${{ inputs.LINUX }}/*.${{ inputs.PACKAGE }}
      # Push package
      - name: Push package to packagecloud
        if: inputs.LINUX != 'el9' && inputs.LINUX != 'ubuntu-noble'
        uses: danielmundi/upload-packagecloud@46cd0e61152bf952dbc0d1759e609d3d22649030 # v1
        with:
          PACKAGE-NAME: /tmp/${{ inputs.LINUX }}/*.${{ inputs.PACKAGE }}
          PACKAGECLOUD-USERNAME: bunkerity
          PACKAGECLOUD-REPO: ${{ inputs.REPO }}
          PACKAGECLOUD-DISTRIB: ${{ inputs.LINUX }}/${{ inputs.VERSION }}
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      - name: Push package to packagecloud for el9
        if: inputs.LINUX == 'el9'
        uses: danielmundi/upload-packagecloud@46cd0e61152bf952dbc0d1759e609d3d22649030 # v1
        with:
          PACKAGE-NAME: /tmp/${{ inputs.LINUX }}/*.${{ inputs.PACKAGE }}
          PACKAGECLOUD-USERNAME: bunkerity
          PACKAGECLOUD-REPO: ${{ inputs.REPO }}
          PACKAGECLOUD-DISTRIB: el/9
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      - name: Push package to packagecloud for ubuntu-noble
        if: inputs.LINUX == 'ubuntu-noble'
        uses: danielmundi/upload-packagecloud@46cd0e61152bf952dbc0d1759e609d3d22649030 # v1
        with:
          PACKAGE-NAME: /tmp/${{ inputs.LINUX }}/*.${{ inputs.PACKAGE }}
          PACKAGECLOUD-USERNAME: bunkerity
          PACKAGECLOUD-REPO: ${{ inputs.REPO }}
          PACKAGECLOUD-DISTRIB: ubuntu/noble
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
