name: Create ARM node (REUSABLE)

on:
  workflow_call:
    secrets:
      SCW_ACCESS_KEY:
        required: true
      SCW_SECRET_KEY:
        required: true
      SCW_DEFAULT_PROJECT_ID:
        required: true
      SCW_DEFAULT_ORGANIZATION_ID:
        required: true
      ARM_ID:
        required: true

jobs:
  rm:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Delete ARM VM
        uses: scaleway/action-scw@be2696f261325a78354eda14988c80405f33e082
        with:
          args: instance server delete ${{ secrets.ARM_ID }} zone=fr-par-2 with-ip=true with-volumes=all force-shutdown=true
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
