name: Push staging packagecloud (REUSABLE)

on:
  workflow_call:
    inputs:
      SEPARATOR:
        required: true
        type: string
      SUFFIX:
        required: true
        type: string
      REPO:
        required: true
        type: string
      LINUX:
        required: true
        type: string
      VERSION:
        required: true
        type: string
      PACKAGE:
        required: true
        type: string
    secrets:
      PACKAGECLOUD_TOKEN:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          VER=$(cat src/VERSION | tr -d '\n')
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install packagecloud
        run: gem install package_cloud
      # Download packages
      - uses: actions/download-artifact@v3
        with:
          name: package-${{ inputs.LINUX }}
          path: /tmp/${{ inputs.LINUX }}
      # Remove existing packages
      - name: Remove existing package
        run: package_cloud yank bunkerity/${{ inputs.REPO }}/${{ inputs.LINUX }}/${{ inputs.VERSION }} bunkerweb${{ inputs.SEPARATOR }}${{ env.VERSION }}${{ inputs.SEPARATOR }}${{ inputs.SUFFIX }}.${{ inputs.PACKAGE }}
        continue-on-error: true
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      # Push package
      - name: Push package to packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: /tmp/${{ inputs.LINUX }}/bunkerweb${{ inputs.SEPARATOR }}${{ env.VERSION }}${{ inputs.SEPARATOR }}${{ inputs.SUFFIX }}.${{ inputs.PACKAGE }}
          PACKAGECLOUD-USERNAME: bunkerity
          PACKAGECLOUD-REPO: ${{ inputs.REPO }}
          PACKAGECLOUD-DISTRIB: ${{ inputs.LINUX }}/${{ input.VERSION }}
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}