name: Automatic tests (UI)

permissions: read-all

on:
  push:
    branches: [ui]

jobs:
  # Containers
  build-containers:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [bunkerweb, scheduler, ui]
        include:
          - image: bunkerweb
            dockerfile: src/bw/Dockerfile
          - image: scheduler
            dockerfile: src/scheduler/Dockerfile
          - image: ui
            dockerfile: src/ui/Dockerfile
    uses: ./.github/workflows/container-build.yml
    with:
      RELEASE: ui
      CACHE: true
      ARCH: linux/amd64
      IMAGE: ${{ matrix.image }}
      DOCKERFILE: ${{ matrix.dockerfile }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  # UI tests
  tests-ui:
    needs: [build-containers]
    uses: ./.github/workflows/tests-ui.yml
    with:
      RELEASE: ui
