name: Automatic tests (UI)

permissions: read-all

on:
  push:
    branches: [ui]

jobs:
  # Containers
  build-containers:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [bunkerweb, scheduler, ui]
        include:
          - image: bunkerweb
            dockerfile: src/bw/Dockerfile
          - image: scheduler
            dockerfile: src/scheduler/Dockerfile
          - image: ui
            dockerfile: src/ui/Dockerfile
    uses: ./.github/workflows/container-build.yml
    with:
      RELEASE: ui
      CACHE: true
      ARCH: linux/amd64
      IMAGE: ${{ matrix.image }}
      DOCKERFILE: ${{ matrix.dockerfile }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  # Build Linux packages
  build-packages:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        linux: [ubuntu]
        include:
          - linux: ubuntu
            package: deb
    uses: ./.github/workflows/linux-build.yml
    with:
      RELEASE: ui
      LINUX: ${{ matrix.linux }}
      PACKAGE: ${{ matrix.package }}
      TEST: true
      PLATFORMS: linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  # UI tests
  tests-ui:
    needs: [codeql, build-containers]
    uses: ./.github/workflows/tests-ui.yml
    with:
      RELEASE: ui
  tests-ui-linux:
    needs: [codeql, build-packages]
    uses: ./.github/workflows/tests-ui-linux.yml
    with:
      RELEASE: ui
